### ISSUE TITLE
非常想试试，但从bird的配置里出现很多IP

### ISSUE THREAD

**Issue by Shane-Meng** [haotianlPM/rosrbgprouter#1]
网络知识很有限，都是干嘛用的，能不能解释一下？看不懂也不知道怎么改。
如果有可能最好能启用一段别的私有IP，比如172.16.x.x 啥的，能和本地网络使用的 IP段有所区分。能避免犯错，多谢

**Comment by KHTdhl** [comment]
要结合着视频教程一起看
