### ISSUE TITLE
感谢脚本！！！

### ISSUE THREAD

**Issue by LwdAmazing** [haotianlPM/rosrbgprouter#2]
教程和视频中有两个问题没有提及，在此提醒小白，
1.  default-nameserver:
    - 192.168.10.9
  nameserver:
    - 192.168.10.9
  proxy-server-nameserver:
    - 192.168.10.9
  nameserver-policy:
    "geosite:cn,private":
      - 192.168.10.9
这里记得换自己的dns的ip。我没理解错的话应该都要换成你自己搭建dns服务器的ip。
2.
interface-name: eth0
这个eth0 要事先ip a 看看自己的LAN口叫什么 然后改一下。

再次感谢大佬脚本。 原理就是MOSDNS+easymosdns+clash-meta。往小白们大力支持点点star

**Comment by KHTdhl** [comment]
是需要换为自己搭建的dns服务器的ip地址，这里视频中没有提到，大家需要自行更换一下。
